#spring:
#  datasource:
#    url: jdbc:h2:file:/data/demo


server:
  port : 8090

endpoints:
  wallet:
    retries: 5
  user:
    retries: 5

    
logging:
  path: "./"
  level:
    com:
      bechtle: TRACE
    org.springframework.security: INFO
    org.springframework.security.saml2: INFO

management:
  endpoint:
    mappings:
      enabled: true
    info:
      git:
        enabled: true
      enabled: true
    logs:
      enabled: true

