#spring:
#  datasource:
#    url: jdbc:h2:file:/data/demo


server:
  port : 8090


spring:
  security:
    saml2:
      relyingparty:
        registration:
          okta:
            attributes:
              uid: "username"
              email: "email"
              firstname: ""
              lastname: ""
            identityprovider:
              entity-id: http://www.okta.com/exk30sqznncnBKwRT5d7
              verification.credentials:
                - certificate-location: "classpath:saml/okta.cert"
              singlesignon.url: https://dev-72526167.okta.com/app/dev-72526167_eaglwebappdemo_1/exk30sqznncnBKwRT5d7/sso/saml
              singlesignon.sign-request: false
          daad:
            attributes:
              uid: "urn:oid:0.9.2342.19200300.100.1.1"
              email: "urn:oid:0.9.2342.19200300.100.1.3"
              firstname: "urn:oid:2.5.4.42"
              lastname: "urn:oid:2.5.4.4"
            identityprovider:
              entity-id: https://saml-bird.daad.com/saml2/idp/metadata.php
              verification.credentials:
                - certificate-location: "classpath:saml/daad-signing.cert"
              singlesignon.url: https://saml-bird.daad.com/saml2/idp/SSOService.php
              singlesignon.sign-request: false


locations:
  metadata:
    okta_azure: "saml/metadata.xml"
    daad: "https://saml-bird.daad.com/saml2/idp/metadata.php"
  certificates:
    signing: "saml/localhost.cer"
    decryption: "saml/localhost.cer"
    verification:
      okta_azure: "saml/okta.cert"
      daad: "saml/daad.cert"
  key: ""

key: ""



