#spring:
#  datasource:
#    url: jdbc:h2:file:/data/demo


server:
  port : 8090

spring:
  profiles:
    active: local
    
logging:
  path: "./"
  level:
    org.springframework.security: DEBUG
    org.springframework.security.saml2: TRACE

management:
  endpoint:
    mappings:
      enabled: true
    info:
      git:
        enabled: true
      enabled: true
    logs:
      enabled: true

